version: '2'
services:
  terraria-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
      - ${config_folder}:/config
  terraria-server:
    image: ${terraria_image}
    ports:
      - "${port}:7777"
    tty: true
    stdin_open: true
    labels:
      io.rancher.sidekicks: terraria-data
    volumes_from:
      - terraria-data